---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - testgroup.daud.com
  resources:
  - yusufs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testgroup.daud.com
  resources:
  - yusufs/finalizers
  verbs:
  - update
- apiGroups:
  - testgroup.daud.com
  resources:
  - yusufs/status
  verbs:
  - get
  - patch
  - update
