# permissions for end users to edit yusufs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: yusuf-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: anaplantest
    app.kubernetes.io/part-of: anaplantest
    app.kubernetes.io/managed-by: kustomize
  name: yusuf-editor-role
rules:
- apiGroups:
  - testgroup.daud.com
  resources:
  - yusufs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testgroup.daud.com
  resources:
  - yusufs/status
  verbs:
  - get
